# Generated by Django 4.1.3 on 2024-04-03 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='patient', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pasport_id', models.CharField(blank=True, max_length=255, verbose_name='Паспорт ID')),
                ('adress', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('medcard', models.CharField(blank=True, max_length=255, verbose_name='Медицинская карта')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
            ],
        ),
    ]
