# Generated by Django 4.1.3 on 2024-04-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0003_alter_doctor_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата обновления'),
        ),
    ]
