# Generated by Django 3.2.1 on 2024-04-17 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='authuser_user',
        ),
    ]
