# Generated by Django 4.1.3 on 2024-04-03 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasport_id', models.CharField(blank=True, max_length=255, verbose_name='Паспорт ID')),
                ('adress', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('medcard', models.CharField(blank=True, max_length=255, verbose_name='Медицинская карта')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Время')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('S', 'Состоялось'), ('A', 'Подтверждено'), ('R', 'Запрошено'), ('C', 'Отменено')], max_length=1, verbose_name='Статус')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.doctor', verbose_name='Врач')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.patient', verbose_name='Пациент')),
            ],
        ),
    ]
