# Generated by Django 4.1.3 on 2024-04-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('A', 'Подтверждено'), ('S', 'Состоялось'), ('R', 'Запрошено'), ('C', 'Отменено')], max_length=1, verbose_name='Статус'),
        ),
    ]
