# Generated by Django 4.1.3 on 2024-04-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('R', 'Запрошено'), ('C', 'Отменено'), ('S', 'Состоялось'), ('A', 'Подтверждено')], max_length=1, verbose_name='Статус'),
        ),
    ]
