# Generated by Django 4.1.3 on 2024-04-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointment_doctor_alter_appointment_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('S', 'Состоялось'), ('A', 'Подтверждено'), ('R', 'Запрошено'), ('C', 'Отменено')], max_length=1, verbose_name='Статус'),
        ),
    ]
