# Generated by Django 4.1.3 on 2024-04-06 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0004_alter_doctor_date_updated_alter_patient_date_updated'),
        ('appointments', '0008_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='authuser.doctor', verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('R', 'Запрошено'), ('S', 'Состоялось'), ('C', 'Отменено'), ('A', 'Подтверждено')], max_length=1, verbose_name='Статус'),
        ),
    ]
