# Generated by Django 3.2.1 on 2024-04-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('S', 'Состоялось'), ('A', 'Подтверждено'), ('C', 'Отменено'), ('R', 'Запрошено')], max_length=1, verbose_name='Статус'),
        ),
    ]
