# Generated by Django 3.2.1 on 2024-04-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('A', 'Подтверждено'), ('R', 'Запрошено'), ('S', 'Состоялось'), ('C', 'Отменено')], max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.DateTimeField(verbose_name='Время (только для чтения)'),
        ),
    ]
